CREATE TABLE USERS (
ID INTEGER NOT NULL IDENTITY, 
USER_NAME VARCHAR(255), 
EMAIL VARCHAR(255), 
PASSWORD VARCHAR(255));

CREATE TABLE EVENTS (
ID INTEGER NOT NULL IDENTITY,
CODE VARCHAR(255),
TITLE VARCHAR(255),
DESCRIPTION VARCHAR(255));

CREATE TABLE REGISTRATIONS (
ID INTEGER NOT NULL IDENTITY,
EVENTID VARCHAR(255),
USERID VARCHAR(255),
REGISTRATIONDATE VARCHAR(255),
NOTES VARCHAR(255));

--ALTER TABLE USERS ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");